### PR TITLE
feature/lisasiliu/notification-page-ui

### LINKED ISSUE #41: [New Account Approval] - Need special card components to be displayed on the UI

### PR DESCRIPTION
**Pull request by lisasiliu**
## Tracking Info

Resolves [#41](https://github.com/TritonSE/PIA-Program-Manager/issues/41) 
#42 

## Changes

Created card component to hold unapproved user details with buttons for approval / denial, created notification table structure (must hardcode each row currently), 

## Testing

Viewed on notifications page (although buttons don't stay on flex box properly at a really thin width)

## Confirmation of Change

image

### CODE REVIEW

**Comment by lisasiliu** [comment]
looks weird on mobile TT 
image

**Review by adhi0331 — CHANGES_REQUESTED** [review]
For some reason the backend in your branch is not up to date with main. Can you make sure that it is? Otherwise we run the risk of breaking everything again. The main issue is that for some reason you have programs stored as program-form when it should just be program. Try merging the main branch with your branch locally and see if that helps update your backend.

**Comment by lisasiliu** [comment]
fixed backend!

**Review by adhi0331 — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
