### PR TITLE
Add Routing and Sidebar

### LINKED ISSUE #5: [ MISC ] - Main Page Routing & SideBar Component
We need to implement the [sidebar component](https://www.figma.com/file/N16keN1mV1QDnorLB1GC6C/Plant-it-Again-(PIA)-Program-Manager?type=design&node-id=1157-13519&mode=design&t=7E2dgN76Hat7Zc6g-0) which allows us to navigate the main page. 

For now don't worry about actually implementing the various pages itself. Just make sure that it changes to the different pages based on which page was clicked. For example if home page was clicked then the home page should be displayed. You can literally have the home page be a simple page that says ("This is the home page") and same for the other pages as well.

Screenshot 2024-01-10 at 12 49 03 AM

### PR DESCRIPTION
**Pull request by parth4apple**
## Tracking Info

Resolves #5 

## Changes
- created `_app.tsx` and `_document.tsx` files for tailwind to work
- made the `Navigation` component which has our Navbar and wraps the application
- created skeleton pages for `/programs`, `/profile`, and `/` and hooked them up to routing
## Testing

Run the frontend and verify that the navbar works as expected on different viewports (mobile, tablet, desktop)

## Confirmation of Change
Screenshot 2024-01-17 at 6 45 07 PM

Screenshot 2024-01-17 at 6 45 27 PM

Screenshot 2024-01-17 at 6 45 40 PM

### CODE REVIEW

**Review by vs2961 — APPROVED** [review]
Looks good to me!

**Comment by aaronchan32** [comment]
Looks great!

**Review by aaronchan32 — APPROVED** [review]
Looks great!

**Review by adhi0331 — CHANGES_REQUESTED** [review]
Looks really good! Just need the notifications tab and this should be good to merge.

**Review by adhi0331 — APPROVED** [review]

**Pull request merged**
