### PR TITLE
feature/jacoblee23/crud-routes: Handle HTTP request types

### LINKED ISSUE #6: [ MISC ] Frontend API - Basic CRUD Routes
We need to setup some functions to call API routes in the function. This includes GET, POST, PUT, PATCH, DELETE. We basically need something like this [file](https://github.com/TritonSE/onboarding/blob/main/frontend/src/api/requests.ts). To test that these functions work feel free to create some test routes on the backend. We just need to make sure that we're able to call the routes.

### PR DESCRIPTION
**Pull request by JacobLee23**
## Tracking Info

Resolves #6

## Changes

- Based on the [TSE onboarding](https://github.com/TritonSE/onboarding/blob/main/frontend/src/api/requests.ts) API client implementation
- Create wrappers for the built-in `fetch()` function to handle GET, POST, PUT, PATCH, and DELETE HTTP requests
  - `fetchRequest()` is a wrapper around the `fetch()` functions, and the `GET()`, `POST()`, `PUT()`, `PATCH()`, and `DELETE()` functions are wrappers around the `fetchRequest()` function.

## Testing

- `GET()`, `POST()`, `PUT()`, `PATCH()`, and `DELETE()` functions tested manually

### `assertOK()`

```ts
const blob = new Blob();
const headers = { status: 200 };
const response = new Response(blob, headers);

// Expected: No effect; Actual: No effect
assertOK(response);
```

```ts
const blob = new Blob();
const headers = { status: 404 };
const response = new Response(blob, headers);

// Expected: Throw `Error`; Actual: Throw `Error`
assertOK(response);
```

### `fetchRequest()`

```ts
GET("https://github.com/");    // Expected: Response status code 200; Actual: Response status code 200
GET("https://url.does.not.exist/");    // Expected: Throw `Error`; Actual: Throw `Error`
POST("https://github.com/", undefined);    // Expected: Response status code 301; Actual: Response status code 301
POST("https://url.does.not.exist/", undefined);    // Expected: throw `Error`; Actual: Throw `Error`
```

_Note: The expected behavior for the above examples was obtained via **Inspect Element**_

### CODE REVIEW

**Review by adhi0331 — APPROVED** [review]
LGTM!!! 🚀

**Review by aaronchan32 — APPROVED** [review]
Looks good!

**Comment by lisasiliu** [comment]
this looks good!

**Review by lisasiliu — APPROVED** [review]
this looks good!

**Pull request merged**
